# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-20.04

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'armEjemplo'
    subscriptionId: 'e3999679-7c37-4f4a-85ab-7fd916a65a47'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'josecitogrupoarm'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/nahuic72/AzureRmPipeline-repo/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName nra'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

